<a href="https://colab.research.google.com/github/Undasnr/DL-ML/blob/main/Ronyy_Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Calculating the Matric Product Manually**
$$
A =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}
$$


$$
B =
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$$


**Solution**

First Row of C

To find the elements of the first row of C, we take the dot product of the first row of A with each column of B.

C11
 : (Row 1 of A) ⋅ (Column 1 of B)

(−1)(0)+(2)(0)+(3)(2)=0+0+6=6

C12
 : (Row 1 of A) ⋅ (Column 2 of B)

(−1)(2)+(2)(2)+(3)(9)=−2+4+27=29

C13
 : (Row 1 of A) ⋅ (Column 3 of B)

(−1)(1)+(2)(−8)+(3)(−1)=−1−16−3=−20

Second Row of C

To find the elements of the second row of C, we take the dot product of the second row of A with each column of B.

C21
 : (Row 2 of A) ⋅ (Column 1 of B)

(4)(0)+(−5)(0)+(6)(2)=0+0+12=12

C22
 : (Row 2 of A) ⋅ (Column 2 of B)

(4)(2)+(−5)(2)+(6)(9)=8−10+54=52

C23
 : (Row 2 of A) ⋅ (Column 3 of B)

(4)(1)+(−5)(−8)+(6)(−1)=4+40−6=38

Third Row of C

To find the elements of the third row of C, we take the dot product of the third row of A with each column of B.

C31
 : (Row 3 of A) ⋅ (Column 1 of B)

(7)(0)+(8)(0)+(−9)(2)=0+0−18=−18

C32
 : (Row 3 of A) ⋅ (Column 2 of B)

(7)(2)+(8)(2)+(−9)(9)=14+16−81=−51

C33
 : (Row 3 of A) ⋅ (Column 3 of B)

(7)(1)+(8)(−8)+(−9)(−1)=7−64+9=−48

The resulting matrix C is:

$$
C =
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}
$$

**Calculating by Numpy function**

In [1]:
import numpy as np

# Defining the matrices as NumPy arrays
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculating the matrix product using np.matmul()
c_matmul = np.matmul(a_ndarray, b_ndarray)
print("Result using np.matmul():")
print(c_matmul)
print("\n" + "-"*30 + "\n")

# Calculating the matrix product using np.dot()
c_dot = np.dot(a_ndarray, b_ndarray)
print("Result using np.dot():")
print(c_dot)
print("\n" + "-"*30 + "\n")

# Calculating the matrix product using the @ operator
c_at_operator = a_ndarray @ b_ndarray
print("Result using the @ operator:")
print(c_at_operator)

Result using np.matmul():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

------------------------------

Result using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

------------------------------

Result using the @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**Scratch Implementation of matrix product**

In [2]:
# Defining the matrices
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Getting the dimensions of the matrices
rows_a, cols_a = a_ndarray.shape
rows_b, cols_b = b_ndarray.shape

# Initializing a new matrix with zeros to store the result
result_ndarray = np.zeros((rows_a, cols_b))

for i in range(rows_a):

    for j in range(cols_b):

        element_sum = 0
        for k in range(cols_a):
            element_sum += a_ndarray[i, k] * b_ndarray[k, j]

        result_ndarray[i, j] = element_sum

print("Result from scratch implementation:")
print(result_ndarray)

Result from scratch implementation:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


**Implementation of Calculation of a certain element**

In [3]:
import numpy as np

# Defining matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculating element (0, 0) manually
result_00 = 0
for k in range(3):  # Since both matrices are 3x3
    result_00 += a_ndarray[0][k] * b_ndarray[k][0]

print("Element (0, 0) of the matrix product is:", result_00)

Element (0, 0) of the matrix product is: 6


**Creating a function that performs matrix multiplication**

In [7]:
import numpy as np

def matrix_product_scratch(A, B):
    # Checking if matrix multiplication is defined
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix product is undefined: columns of A must equal rows of B.")

    # Getting dimensions
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Initializing result matrix with zeros
    result = np.zeros((rows_A, cols_B), dtype=int)

    # Performing manual matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):  # or rows_B
                result[i][j] += A[i][k] * B[k][j]

    return result

# Defining matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

product_result = matrix_product_scratch(a_ndarray, b_ndarray)
print("Matrix product (scratch):\n", product_result)

Matrix product (scratch):
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**Undefined matrix multiplication**

In [9]:
#Undefined matrices
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])  # Shape: (2, 3)
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])  # Shape: (2, 3)

try:
    result = matrix_product_scratch(d_ndarray, e_ndarray)
except ValueError as e:
    print("Error:", e)

Error: Matrix product is undefined: columns of A must equal rows of B.


**Judging the input whose calculation is not defined**

In [10]:
def matrix_product_scratch(A, B):
    # Checking if matrix multiplication is defined
    if A.shape[1] != B.shape[0]:
        print(f"Matrix product is undefined:")
        print(f"Matrix A shape: {A.shape} (columns: {A.shape[1]})")
        print(f"Matrix B shape: {B.shape} (rows: {B.shape[0]})")
        print("Matrix multiplication requires columns of A to equal rows of B.")
        return None

    # Initializing result matrix
    result = np.zeros((A.shape[0], B.shape[1]), dtype=int)

    # Manual matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]

    return result

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])  # Shape: (2, 3)
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])  # Shape: (2, 3)

result = matrix_product_scratch(d_ndarray, e_ndarray)

Matrix product is undefined:
Matrix A shape: (2, 3) (columns: 3)
Matrix B shape: (2, 3) (rows: 2)
Matrix multiplication requires columns of A to equal rows of B.


**Transposition to enable multiplication**

In [12]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Transposing matrix E using the .T attribute
e_transposed = e_ndarray.T
print("Original matrix E:")
print(e_ndarray)
print("\nTransposed matrix E^T:")
print(e_transposed)

# Using the @ operator to find the matrix product of D and the transposed E
result_product = d_ndarray @ e_transposed

print("\nResult of D @ E.T:")
print(result_product)

Original matrix E:
[[-9  8  7]
 [ 6 -5  4]]

Transposed matrix E^T:
[[-9  6]
 [ 8 -5]
 [ 7  4]]

Result of D @ E.T:
[[ 46  -4]
 [-34  73]]
